AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  EnvironmentName:
    Type: String
    
Resources:
  LargeFileTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${EnvironmentName}-LargeFileTopic"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
          
  DataTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${EnvironmentName}-DataTeamTopic"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName  
          
  FinanceTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${EnvironmentName}-FinanceTeamTopic"
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
          
  LargeFileSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: azamiheme19@gmail.com
      Protocol: email
      TopicArn: !Ref LargeFileTopic
      
  DataTeamSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: azamiheme19@gmail.com
      Protocol: email
      TopicArn: !Ref DataTeamTopic
      
  FinanceTeamSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: azamiheme19@gmail.com
      Protocol: email
      TopicArn: !Ref FinanceTeamTopic
      
Outputs:
  LargeFileTopicName:
    Value: !Ref LargeFileTopic
    
  DataTeamTopicName:
    Value: !Ref DataTeamTopic
    
  FinanceTeamTopicName:
    Value: !Ref FinanceTeamTopic
